package Util;

import java.applet.Applet;
import java.applet.AudioClip;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URI;

public class WAVUtil {
        public static void wav(String s) throws MalformedURLException {
            switch(s){
                case ("0"):File file_0 = new File("C:\\Users\\86133\\Documents\\Code\\JAVA\\Java-TwinCalculater\\src\\SoundSource_WAV\\0.wav");
                    URI uri_0 = file_0.toURI();
                    System.out.println(uri_0);
                    AudioClip audioClip_0 = Applet.newAudioClip(uri_0.toURL());
                    audioClip_0.play();
                    break;
                case ("1"):File file_1 = new File("C:\\Users\\86133\\Documents\\Code\\JAVA\\Java-TwinCalculater\\src\\SoundSource_WAV\\1.wav");
                    URI uri_1 = file_1.toURI();
                    System.out.println(uri_1);
                    AudioClip audioClip_1 = Applet.newAudioClip(uri_1.toURL());
                    audioClip_1.play();
                    break;
                case ("2"):File file_2 = new File("C:\\Users\\86133\\Documents\\Code\\JAVA\\Java-TwinCalculater\\src\\SoundSource_WAV\\2.wav");
                    URI uri_2 = file_2.toURI();
                    System.out.println(uri_2);
                    AudioClip audioClip_2 = Applet.newAudioClip(uri_2.toURL());
                    audioClip_2.play();
                    break;
                case ("3"):File file_3 = new File("C:\\Users\\86133\\Documents\\Code\\JAVA\\Java-TwinCalculater\\src\\SoundSource_WAV\\3.wav");
                    URI uri_3 = file_3.toURI();
                    System.out.println(uri_3);
                    AudioClip audioClip_3 = Applet.newAudioClip(uri_3.toURL());
                    audioClip_3.play();
                    break;
                case ("4"):File file_4 = new File("C:\\Users\\86133\\Documents\\Code\\JAVA\\Java-TwinCalculater\\src\\SoundSource_WAV\\4.wav");
                    URI uri_4 = file_4.toURI();
                    System.out.println(uri_4);
                    AudioClip audioClip_4 = Applet.newAudioClip(uri_4.toURL());
                    audioClip_4.play();
                    break;
                case ("5"):File file_5 = new File("C:\\Users\\86133\\Documents\\Code\\JAVA\\Java-TwinCalculater\\src\\SoundSource_WAV\\5.wav");
                    URI uri_5 = file_5.toURI();
                    System.out.println(uri_5);
                    AudioClip audioClip_5 = Applet.newAudioClip(uri_5.toURL());
                    audioClip_5.play();
                    break;
                case ("6"):File file_6 = new File("C:\\Users\\86133\\Documents\\Code\\JAVA\\Java-TwinCalculater\\src\\SoundSource_WAV\\6.wav");
                    URI uri_6 = file_6.toURI();
                    System.out.println(uri_6);
                    AudioClip audioClip_6 = Applet.newAudioClip(uri_6.toURL());
                    audioClip_6.play();
                    break;
                case ("7"):File file_7 = new File("C:\\Users\\86133\\Documents\\Code\\JAVA\\Java-TwinCalculater\\src\\SoundSource_WAV\\7.wav");
                    URI uri_7 = file_7.toURI();
                    System.out.println(uri_7);
                    AudioClip audioClip_7 = Applet.newAudioClip(uri_7.toURL());
                    audioClip_7.play();
                    break;
                case ("8"):File file_8 = new File("C:\\Users\\86133\\Documents\\Code\\JAVA\\Java-TwinCalculater\\src\\SoundSource_WAV\\8.wav");
                    URI uri_8 = file_8.toURI();
                    System.out.println(uri_8);
                    AudioClip audioClip_8 = Applet.newAudioClip(uri_8.toURL());
                    audioClip_8.play();
                    break;
                case ("9"):File file_9 = new File("C:\\Users\\86133\\Documents\\Code\\JAVA\\Java-TwinCalculater\\src\\SoundSource_WAV\\9.wav");
                    URI uri_9 = file_9.toURI();
                    System.out.println(uri_9);
                    AudioClip audioClip_9 = Applet.newAudioClip(uri_9.toURL());
                    audioClip_9.play();
                    break;
                case ("+"):File file_add = new File("C:\\Users\\86133\\Documents\\Code\\JAVA\\Java-TwinCalculater\\src\\SoundSource_WAV\\Jia.wav");
                    URI uri_add = file_add.toURI();
                    System.out.println(uri_add);
                    AudioClip audioClip_add = Applet.newAudioClip(uri_add.toURL());
                    audioClip_add.play();
                    break;
                case ("-"):File file_sub = new File("C:\\Users\\86133\\Documents\\Code\\JAVA\\Java-TwinCalculater\\src\\SoundSource_WAV\\Jian.wav");
                    URI uri_sub = file_sub.toURI();
                    System.out.println(uri_sub);
                    AudioClip audioClip_sub = Applet.newAudioClip(uri_sub.toURL());
                    audioClip_sub.play();
                    break;
                case ("*"):File file_mul = new File("C:\\Users\\86133\\Documents\\Code\\JAVA\\Java-TwinCalculater\\src\\SoundSource_WAV\\Cheng.wav");
                    URI uri_mul = file_mul.toURI();
                    System.out.println(uri_mul);
                    AudioClip audioClip_mul = Applet.newAudioClip(uri_mul.toURL());
                    audioClip_mul.play();
                    break;
                case ("/"):File file_div = new File("C:\\Users\\86133\\Documents\\Code\\JAVA\\Java-TwinCalculater\\src\\SoundSource_WAV\\Chu.wav");
                    URI uri_div = file_div.toURI();
                    System.out.println(uri_div);
                    AudioClip audioClip_div = Applet.newAudioClip(uri_div.toURL());
                    audioClip_div.play();
                    break;
                case ("."):File file_dot = new File("C:\\Users\\86133\\Documents\\Code\\JAVA\\Java-TwinCalculater\\src\\SoundSource_WAV\\Dian.wav");
                    URI uri_dot = file_dot.toURI();
                    System.out.println(uri_dot);
                    AudioClip audioClip_dot = Applet.newAudioClip(uri_dot.toURL());
                    audioClip_dot.play();
                    break;
                case ("="):File file_equ = new File("C:\\Users\\86133\\Documents\\Code\\JAVA\\Java-TwinCalculater\\src\\SoundSource_WAV\\DengYu.wav");
                    URI uri_equ = file_equ.toURI();
                    System.out.println(uri_equ);
                    AudioClip audioClip_equ = Applet.newAudioClip(uri_equ.toURL());
                    audioClip_equ.play();
                    break;
                case ("sr"):File file_sr = new File("C:\\Users\\86133\\Documents\\Code\\JAVA\\Java-TwinCalculater\\src\\SoundSource_WAV\\YouYi.wav");
                    URI uri_sr = file_sr.toURI();
                    System.out.println(uri_sr);
                    AudioClip audioClip_sr = Applet.newAudioClip(uri_sr.toURL());
                    audioClip_sr.play();
                    break;
                case ("sl"):File file_sl = new File("C:\\Users\\86133\\Documents\\Code\\JAVA\\Java-TwinCalculater\\src\\SoundSource_WAV\\ZuoYi.wav");
                    URI uri_sl = file_sl.toURI();
                    System.out.println(uri_sl);
                    AudioClip audioClip_sl = Applet.newAudioClip(uri_sl.toURL());
                    audioClip_sl.play();
                    break;
                case ("clr"):File file_clr = new File("C:\\Users\\86133\\Documents\\Code\\JAVA\\Java-TwinCalculater\\src\\SoundSource_WAV\\Classic_GuiLing.wav");
                    URI uri_clr = file_clr.toURI();
                    System.out.println(uri_clr);
                    AudioClip audioClip_clr = Applet.newAudioClip(uri_clr.toURL());
                    audioClip_clr.play();
                    break;
            }
    }

}
